#!/usr/bin/env python3

import os
import sqlite3
from pathlib import Path

DB_PATH = os.environ.get("FILAMENT_DB_PATH", "filament.db")

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

# ============================================================================
# PERFIS DE PROCESSO PARA PLA
# ============================================================================

# PLA - Rápido (Fast)
pla_fast = {
    "material_id": 1,  # Será atualizado após buscar o ID correto
    "profile_name": "0.28mm Fast @Creality K2 0.4 nozzle - PLA",
    "profile_type": "fast",
    "layer_height": 0.28,
    "initial_layer_height": 0.36,
    "inner_wall_speed": 450,
    "outer_wall_speed": 350,
    "sparse_infill_speed": 450,
    "internal_solid_infill_speed": 400,
    "top_surface_speed": 350,
    "initial_layer_speed": 60,
    "travel_speed": 600,
    "support_speed": 150,
    "gap_infill_speed": 100,
    "default_acceleration": 10000,
    "inner_wall_acceleration": 6000,
    "outer_wall_acceleration": 5000,
    "top_surface_acceleration": 5000,
    "wall_loops": 2,
    "wall_generator": "arachne",
    "wall_sequence": "inner wall/outer wall",
    "sparse_infill_density": "15%",
    "sparse_infill_pattern": "gyroid",
    "internal_solid_infill_pattern": "monotonic",
    "infill_combination": 0,
    "top_surface_pattern": "monotonic",
    "bottom_surface_pattern": "monotonic",
    "top_shell_layers": 3,
    "bottom_shell_layers": 3,
    "top_shell_thickness": 0.84,
    "bottom_shell_thickness": 0.84,
    "enable_support": 1,
    "support_type": "tree(auto)",
    "support_on_build_plate_only": 1,
    "support_top_z_distance": 0.25,
    "support_interface_spacing": 0.8,
    "support_interface_top_layers": 2,
    "support_object_xy_distance": 0.4,
    "support_xy_overrides_z": "z_overrides_xy",
    "brim_width": 5,
    "brim_object_gap": 0.2,
    "ironing_type": "no ironing",
    "seam_position": "aligned",
    "inherits": "0.20mm Standard @Creality K2 0.4 nozzle",
    "description": "Perfil rápido para PLA - otimizado para velocidade com qualidade aceitável",
    "notes": "Ideal para protótipos rápidos e peças onde a velocidade é mais importante que o acabamento perfeito",
    "active": 1
}

# PLA - Padrão (Standard)
pla_standard = {
    "material_id": 1,
    "profile_name": "0.20mm Standard @Creality K2 0.4 nozzle - PLA",
    "profile_type": "standard",
    "layer_height": 0.2,
    "initial_layer_height": 0.28,
    "inner_wall_speed": 300,
    "outer_wall_speed": 200,
    "sparse_infill_speed": 300,
    "internal_solid_infill_speed": 250,
    "top_surface_speed": 200,
    "initial_layer_speed": 40,
    "travel_speed": 450,
    "support_speed": 100,
    "gap_infill_speed": 80,
    "default_acceleration": 5000,
    "inner_wall_acceleration": 3500,
    "outer_wall_acceleration": 3000,
    "top_surface_acceleration": 3000,
    "wall_loops": 3,
    "wall_generator": "arachne",
    "wall_sequence": "inner wall/outer wall",
    "sparse_infill_density": "20%",
    "sparse_infill_pattern": "gyroid",
    "internal_solid_infill_pattern": "monotonic",
    "infill_combination": 0,
    "top_surface_pattern": "monotonic",
    "bottom_surface_pattern": "monotonic",
    "top_shell_layers": 4,
    "bottom_shell_layers": 4,
    "top_shell_thickness": 0.8,
    "bottom_shell_thickness": 0.8,
    "enable_support": 1,
    "support_type": "tree(auto)",
    "support_on_build_plate_only": 1,
    "support_top_z_distance": 0.2,
    "support_interface_spacing": 0.6,
    "support_interface_top_layers": 3,
    "support_object_xy_distance": 0.4,
    "support_xy_overrides_z": "z_overrides_xy",
    "brim_width": 6,
    "brim_object_gap": 0.15,
    "ironing_type": "no ironing",
    "seam_position": "aligned",
    "inherits": "0.20mm Standard @Creality K2 0.4 nozzle",
    "description": "Perfil padrão para PLA - equilibrado entre velocidade e qualidade",
    "notes": "Ideal para uso geral, peças funcionais e protótipos com bom acabamento",
    "active": 1
}

# PLA - Resistente (Strong)
pla_strong = {
    "material_id": 1,
    "profile_name": "0.24mm Strong @Creality K2 0.4 nozzle - PLA",
    "profile_type": "strong",
    "layer_height": 0.24,
    "initial_layer_height": 0.32,
    "inner_wall_speed": 250,
    "outer_wall_speed": 180,
    "sparse_infill_speed": 250,
    "internal_solid_infill_speed": 220,
    "top_surface_speed": 180,
    "initial_layer_speed": 35,
    "travel_speed": 400,
    "support_speed": 100,
    "gap_infill_speed": 70,
    "default_acceleration": 4000,
    "inner_wall_acceleration": 2500,
    "outer_wall_acceleration": 2000,
    "top_surface_acceleration": 2000,
    "wall_loops": 4,
    "wall_generator": "arachne",
    "wall_sequence": "inner wall/outer wall",
    "sparse_infill_density": "40%",
    "sparse_infill_pattern": "gyroid",
    "internal_solid_infill_pattern": "gyroid",
    "infill_combination": 1,
    "top_surface_pattern": "zig-zag",
    "bottom_surface_pattern": "zig-zag",
    "top_shell_layers": 5,
    "bottom_shell_layers": 5,
    "top_shell_thickness": 1.2,
    "bottom_shell_thickness": 1.2,
    "enable_support": 1,
    "support_type": "tree(auto)",
    "support_on_build_plate_only": 1,
    "support_top_z_distance": 0.2,
    "support_interface_spacing": 0.6,
    "support_interface_top_layers": 4,
    "support_object_xy_distance": 0.5,
    "support_xy_overrides_z": "z_overrides_xy",
    "brim_width": 10,
    "brim_object_gap": 0.1,
    "ironing_type": "no ironing",
    "seam_position": "back",
    "inherits": "0.20mm Standard @Creality K2 0.4 nozzle",
    "description": "Perfil resistente para PLA - otimizado para máxima resistência mecânica",
    "notes": "Ideal para peças funcionais que precisam de alta resistência e durabilidade",
    "active": 1
}

# PLA - Caprichado/Qualidade (Quality)
pla_quality = {
    "material_id": 1,
    "profile_name": "0.16mm Quality @Creality K2 0.4 nozzle - PLA",
    "profile_type": "quality",
    "layer_height": 0.16,
    "initial_layer_height": 0.24,
    "inner_wall_speed": 180,
    "outer_wall_speed": 120,
    "sparse_infill_speed": 200,
    "internal_solid_infill_speed": 150,
    "top_surface_speed": 100,
    "initial_layer_speed": 30,
    "travel_speed": 350,
    "support_speed": 80,
    "gap_infill_speed": 60,
    "default_acceleration": 2500,
    "inner_wall_acceleration": 2000,
    "outer_wall_acceleration": 1500,
    "top_surface_acceleration": 1500,
    "wall_loops": 5,
    "wall_generator": "arachne",
    "wall_sequence": "outer wall/inner wall",
    "sparse_infill_density": "20%",
    "sparse_infill_pattern": "gyroid",
    "internal_solid_infill_pattern": "hilbertcurve",
    "infill_combination": 1,
    "top_surface_pattern": "zig-zag",
    "bottom_surface_pattern": "zig-zag",
    "top_shell_layers": 6,
    "bottom_shell_layers": 6,
    "top_shell_thickness": 0.96,
    "bottom_shell_thickness": 0.96,
    "enable_support": 1,
    "support_type": "tree(auto)",
    "support_on_build_plate_only": 1,
    "support_top_z_distance": 0.2,
    "support_interface_spacing": 0.4,
    "support_interface_top_layers": 4,
    "support_object_xy_distance": 0.4,
    "support_xy_overrides_z": "z_overrides_xy",
    "brim_width": 12,
    "brim_object_gap": 0.1,
    "ironing_type": "topmost",
    "seam_position": "back",
    "inherits": "0.20mm Standard @Creality K2 0.4 nozzle",
    "description": "Perfil qualidade para PLA - otimizado para melhor acabamento superficial",
    "notes": "Ideal para peças estéticas, modelos de exibição e quando o acabamento visual é prioridade",
    "active": 1
}

# ============================================================================
# PERFIS DE PROCESSO PARA PETG
# ============================================================================

# PETG - Rápido (Fast)
petg_fast = {
    "material_id": 2,  # Será atualizado após buscar o ID correto
    "profile_name": "0.28mm Fast @Creality K2 0.4 nozzle - PETG",
    "profile_type": "fast",
    "layer_height": 0.28,
    "initial_layer_height": 0.36,
    "inner_wall_speed": 300,
    "outer_wall_speed": 220,
    "sparse_infill_speed": 300,
    "internal_solid_infill_speed": 250,
    "top_surface_speed": 220,
    "initial_layer_speed": 50,
    "travel_speed": 500,
    "support_speed": 120,
    "gap_infill_speed": 90,
    "default_acceleration": 6000,
    "inner_wall_acceleration": 4000,
    "outer_wall_acceleration": 3000,
    "top_surface_acceleration": 3000,
    "wall_loops": 3,
    "wall_generator": "arachne",
    "wall_sequence": "inner wall/outer wall",
    "sparse_infill_density": "15%",
    "sparse_infill_pattern": "gyroid",
    "internal_solid_infill_pattern": "monotonic",
    "infill_combination": 0,
    "top_surface_pattern": "monotonic",
    "bottom_surface_pattern": "monotonic",
    "top_shell_layers": 4,
    "bottom_shell_layers": 4,
    "top_shell_thickness": 1.12,
    "bottom_shell_thickness": 1.12,
    "enable_support": 1,
    "support_type": "tree(auto)",
    "support_on_build_plate_only": 1,
    "support_top_z_distance": 0.25,
    "support_interface_spacing": 0.8,
    "support_interface_top_layers": 3,
    "support_object_xy_distance": 0.5,
    "support_xy_overrides_z": "z_overrides_xy",
    "brim_width": 6,
    "brim_object_gap": 0.16,
    "ironing_type": "no ironing",
    "seam_position": "aligned",
    "inherits": "0.20mm Standard @Creality K2 0.4 nozzle",
    "description": "Perfil rápido para PETG - otimizado para velocidade com qualidade aceitável",
    "notes": "Ideal para protótipos rápidos em PETG onde a velocidade é mais importante que o acabamento perfeito",
    "active": 1
}

# PETG - Padrão (Standard)
petg_standard = {
    "material_id": 2,
    "profile_name": "0.20mm Standard @Creality K2 0.4 nozzle - PETG",
    "profile_type": "standard",
    "layer_height": 0.2,
    "initial_layer_height": 0.28,
    "inner_wall_speed": 200,
    "outer_wall_speed": 140,
    "sparse_infill_speed": 200,
    "internal_solid_infill_speed": 180,
    "top_surface_speed": 140,
    "initial_layer_speed": 35,
    "travel_speed": 400,
    "support_speed": 90,
    "gap_infill_speed": 70,
    "default_acceleration": 4000,
    "inner_wall_acceleration": 3000,
    "outer_wall_acceleration": 2500,
    "top_surface_acceleration": 2500,
    "wall_loops": 3,
    "wall_generator": "arachne",
    "wall_sequence": "inner wall/outer wall",
    "sparse_infill_density": "20%",
    "sparse_infill_pattern": "gyroid",
    "internal_solid_infill_pattern": "monotonic",
    "infill_combination": 0,
    "top_surface_pattern": "monotonic",
    "bottom_surface_pattern": "monotonic",
    "top_shell_layers": 4,
    "bottom_shell_layers": 4,
    "top_shell_thickness": 0.8,
    "bottom_shell_thickness": 0.8,
    "enable_support": 1,
    "support_type": "tree(auto)",
    "support_on_build_plate_only": 1,
    "support_top_z_distance": 0.2,
    "support_interface_spacing": 0.6,
    "support_interface_top_layers": 3,
    "support_object_xy_distance": 0.45,
    "support_xy_overrides_z": "z_overrides_xy",
    "brim_width": 8,
    "brim_object_gap": 0.15,
    "ironing_type": "no ironing",
    "seam_position": "aligned",
    "inherits": "0.20mm Standard @Creality K2 0.4 nozzle",
    "description": "Perfil padrão para PETG - equilibrado entre velocidade e qualidade",
    "notes": "Ideal para uso geral em PETG, peças funcionais e protótipos com bom acabamento",
    "active": 1
}

# PETG - Resistente (Strong)
petg_strong = {
    "material_id": 2,
    "profile_name": "0.24mm Strong @Creality K2 0.4 nozzle - PETG",
    "profile_type": "strong",
    "layer_height": 0.24,
    "initial_layer_height": 0.32,
    "inner_wall_speed": 150,
    "outer_wall_speed": 100,
    "sparse_infill_speed": 180,
    "internal_solid_infill_speed": 150,
    "top_surface_speed": 100,
    "initial_layer_speed": 35,
    "travel_speed": 350,
    "support_speed": 100,
    "gap_infill_speed": 70,
    "default_acceleration": 4000,
    "inner_wall_acceleration": 2500,
    "outer_wall_acceleration": 2000,
    "top_surface_acceleration": 2000,
    "wall_loops": 5,
    "wall_generator": "arachne",
    "wall_sequence": "inner wall/outer wall",
    "sparse_infill_density": "50%",
    "sparse_infill_pattern": "gyroid",
    "internal_solid_infill_pattern": "gyroid",
    "infill_combination": 1,
    "top_surface_pattern": "zig-zag",
    "bottom_surface_pattern": "zig-zag",
    "top_shell_layers": 6,
    "bottom_shell_layers": 6,
    "top_shell_thickness": 1.44,
    "bottom_shell_thickness": 1.44,
    "enable_support": 1,
    "support_type": "tree(auto)",
    "support_on_build_plate_only": 1,
    "support_top_z_distance": 0.2,
    "support_interface_spacing": 0.6,
    "support_interface_top_layers": 4,
    "support_object_xy_distance": 0.5,
    "support_xy_overrides_z": "z_overrides_xy",
    "brim_width": 10,
    "brim_object_gap": 0.16,
    "ironing_type": "no ironing",
    "seam_position": "back",
    "inherits": "0.20mm Standard @Creality K2 0.4 nozzle",
    "description": "Perfil resistente para PETG - otimizado para máxima resistência mecânica",
    "notes": "Ideal para peças funcionais em PETG que precisam de alta resistência e durabilidade",
    "active": 1
}

# PETG - Caprichado/Qualidade (Quality)
petg_quality = {
    "material_id": 2,
    "profile_name": "0.16mm Quality @Creality K2 0.4 nozzle - PETG",
    "profile_type": "quality",
    "layer_height": 0.16,
    "initial_layer_height": 0.24,
    "inner_wall_speed": 120,
    "outer_wall_speed": 80,
    "sparse_infill_speed": 150,
    "internal_solid_infill_speed": 100,
    "top_surface_speed": 80,
    "initial_layer_speed": 30,
    "travel_speed": 300,
    "support_speed": 80,
    "gap_infill_speed": 60,
    "default_acceleration": 2500,
    "inner_wall_acceleration": 2000,
    "outer_wall_acceleration": 1500,
    "top_surface_acceleration": 1500,
    "wall_loops": 6,
    "wall_generator": "arachne",
    "wall_sequence": "outer wall/inner wall",
    "sparse_infill_density": "25%",
    "sparse_infill_pattern": "gyroid",
    "internal_solid_infill_pattern": "hilbertcurve",
    "infill_combination": 1,
    "top_surface_pattern": "zig-zag",
    "bottom_surface_pattern": "zig-zag",
    "top_shell_layers": 7,
    "bottom_shell_layers": 7,
    "top_shell_thickness": 1.12,
    "bottom_shell_thickness": 1.12,
    "enable_support": 1,
    "support_type": "tree(auto)",
    "support_on_build_plate_only": 1,
    "support_top_z_distance": 0.2,
    "support_interface_spacing": 0.4,
    "support_interface_top_layers": 4,
    "support_object_xy_distance": 0.4,
    "support_xy_overrides_z": "z_overrides_xy",
    "brim_width": 12,
    "brim_object_gap": 0.16,
    "ironing_type": "no ironing",
    "seam_position": "back",
    "inherits": "0.20mm Standard @Creality K2 0.4 nozzle",
    "description": "Perfil qualidade para PETG - otimizado para melhor acabamento superficial",
    "notes": "Ideal para peças estéticas em PETG, modelos de exibição e quando o acabamento visual é prioridade",
    "active": 1
}

# ============================================================================
# INSERIR PERFIS NO BANCO
# ============================================================================

# Buscar IDs dos materiais
cur.execute("SELECT id FROM materials WHERE name = 'PLA'")
pla_id = cur.fetchone()
if pla_id:
    pla_id = pla_id[0]
else:
    print("ERRO: Material PLA não encontrado no banco de dados")
    exit(1)

cur.execute("SELECT id FROM materials WHERE name = 'PETG'")
petg_id = cur.fetchone()
if petg_id:
    petg_id = petg_id[0]
else:
    print("ERRO: Material PETG não encontrado no banco de dados")
    exit(1)

# Atualizar IDs nos perfis
pla_fast["material_id"] = pla_id
pla_standard["material_id"] = pla_id
pla_strong["material_id"] = pla_id
pla_quality["material_id"] = pla_id

petg_fast["material_id"] = petg_id
petg_standard["material_id"] = petg_id
petg_strong["material_id"] = petg_id
petg_quality["material_id"] = petg_id

# Inserir perfis
profiles = [pla_fast, pla_standard, pla_strong, pla_quality, petg_fast, petg_standard, petg_strong, petg_quality]

for profile in profiles:
    cur.execute("""
        INSERT INTO process_profiles(
            material_id,
            profile_name,
            profile_type,
            layer_height,
            initial_layer_height,
            inner_wall_speed,
            outer_wall_speed,
            sparse_infill_speed,
            internal_solid_infill_speed,
            top_surface_speed,
            initial_layer_speed,
            travel_speed,
            support_speed,
            gap_infill_speed,
            default_acceleration,
            inner_wall_acceleration,
            outer_wall_acceleration,
            top_surface_acceleration,
            wall_loops,
            wall_generator,
            wall_sequence,
            sparse_infill_density,
            sparse_infill_pattern,
            internal_solid_infill_pattern,
            infill_combination,
            top_surface_pattern,
            bottom_surface_pattern,
            top_shell_layers,
            bottom_shell_layers,
            top_shell_thickness,
            bottom_shell_thickness,
            enable_support,
            support_type,
            support_on_build_plate_only,
            support_top_z_distance,
            support_interface_spacing,
            support_interface_top_layers,
            support_object_xy_distance,
            support_xy_overrides_z,
            brim_width,
            brim_object_gap,
            ironing_type,
            seam_position,
            printer_model,
            nozzle_size,
            base_id,
            inherits,
            version,
            description,
            notes,
            active
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        profile["material_id"],
        profile["profile_name"],
        profile["profile_type"],
        profile["layer_height"],
        profile["initial_layer_height"],
        profile["inner_wall_speed"],
        profile["outer_wall_speed"],
        profile["sparse_infill_speed"],
        profile["internal_solid_infill_speed"],
        profile["top_surface_speed"],
        profile["initial_layer_speed"],
        profile["travel_speed"],
        profile["support_speed"],
        profile["gap_infill_speed"],
        profile["default_acceleration"],
        profile["inner_wall_acceleration"],
        profile["outer_wall_acceleration"],
        profile["top_surface_acceleration"],
        profile["wall_loops"],
        profile["wall_generator"],
        profile["wall_sequence"],
        profile["sparse_infill_density"],
        profile["sparse_infill_pattern"],
        profile["internal_solid_infill_pattern"],
        profile["infill_combination"],
        profile["top_surface_pattern"],
        profile["bottom_surface_pattern"],
        profile["top_shell_layers"],
        profile["bottom_shell_layers"],
        profile["top_shell_thickness"],
        profile["bottom_shell_thickness"],
        profile["enable_support"],
        profile["support_type"],
        profile["support_on_build_plate_only"],
        profile["support_top_z_distance"],
        profile["support_interface_spacing"],
        profile["support_interface_top_layers"],
        profile["support_object_xy_distance"],
        profile["support_xy_overrides_z"],
        profile["brim_width"],
        profile["brim_object_gap"],
        profile["ironing_type"],
        profile["seam_position"],
        profile.get("printer_model", "Creality K2 Combo"),
        profile.get("nozzle_size", 0.4),
        profile.get("base_id", "GP004"),
        profile["inherits"],
        profile.get("version", "26.4.28.18"),
        profile["description"],
        profile["notes"],
        profile["active"]
    ))
    
    print(f"Inserido: {profile['profile_name']}")

conn.commit()
conn.close()

print("Seed de perfis de processo concluído com sucesso!")
